theme: minima

title: FPT4
description: >- # this means to ignore newlines until "baseurl:"
 FPT-4 ANR Project

url: "https://ddavid42.github.io/fpt4/"

header_pages:
 - index.md
 - consortium.md
 - publications.md


permalinks: pretty
markdown: kramdown

exclude:
   - Gemfile
   - Gemfile.lock
